#!/usr/bin/env python3
"""Generate Crossroads 1.0 language packs from a canonical English catalog."""
from __future__ import annotations

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1] / "src/main/resources/lang"

# bundle -> key -> english
EN: dict[str, dict[str, str]] = {
    "common.yml": {
        "no-permission": "<error>You do not have permission for that.",
        "players-only": "<error>This command can only be used in-game.",
        "feature-disabled": "<error>That feature is disabled in the Crossroads config.",
        "cooldown": "<error>That command is on cooldown for another <warn>%duration%<error>.",
        "player-not-online": "<error>That player is not online.",
        "player-not-found": "<error>No known player named <warn>%player%<error> was found.",
        "world-not-loaded": "<error>That location points to a world that is not loaded.",
        "unknown-command": "<error>Unknown Crossroads subcommand.",
    },
    "travel.yml": {
        "home.not-found": "<error>You do not have a home named <warn>%home%<error>.",
        "home.world-unloaded": "<error>That home points to a world that is not loaded.",
        "home.cancelled": "<error>Your home teleport was cancelled.",
        "home.limit": "<error>You have reached your home limit of <warn>%limit%<error> in <warn>%scope%<error>.",
        "home.saved": "<success>Saved home <warn>%home%<success> at <text>%location%",
        "home.deleted-missing": "<error>No home named <warn>%home%<error> exists.",
        "home.deleted": "<success>Deleted home <warn>%home%<success>.",
        "home.none": "<subtle>You have not set any homes yet.",
        "home.list": "<warn>Your homes<subtle>: <text>%homes%",
        "home.teleported": "<success>Welcome back to home <warn>%home%<success>.",
        "warp.none-available": "<subtle>No warps are available right now.",
        "warp.available": "<info>Available warps<subtle>: <text>%warps%",
        "warp.unknown": "<error>Unknown warp <warn>%warp%<error>.",
        "warp.world-unloaded": "<error>That warp points to a world that is not loaded.",
        "warp.usage-set": "<error>Usage: <warn>/setwarp [profile:]<name>",
        "warp.saved": "<success>Saved warp <warn>%warp%<success> at <text>%location%",
        "warp.usage-del": "<error>Usage: <warn>/delwarp [profile:]<name>",
        "warp.deleted": "<success>Deleted warp <warn>%warp%<success>.",
        "warp.none-created": "<subtle>No warps have been created yet.",
        "warp.list": "<warn>Warps<subtle>: <text>%warps%",
        "warp.teleported": "<success>Warped to <warn>%warp%<success>.",
        "spawn.missing": "<error>Spawn has not been configured yet.",
        "spawn.world-unloaded": "<error>Spawn points to a world that is not loaded.",
        "spawn.updated": "<success>Spawn profile <warn>%profile%<success> updated to <text>%location%",
        "spawn.teleported": "<success>Teleported to spawn.",
        "back.missing": "<error>No previous location is available yet.",
        "back.world-unloaded": "<error>Your back location points to a world that is not loaded.",
        "back.teleported": "<success>Returned to your previous location.",
        "tpa.usage": "<error>Usage: <warn>/tpa <player>",
        "tpahere.usage": "<error>Usage: <warn>/tpahere <player>",
        "tpa.self": "<error>You cannot send a teleport request to yourself.",
        "tpa.sent": "<success>Teleport request sent to <warn>%player%<success>.",
        "tpa.incoming": "<info>%player% <text>requested to teleport to you. Use <warn>/tpaccept <text>or <warn>/tpdeny<text>.",
        "tpahere.incoming": "<info>%player% <text>requested that you teleport to them. Use <warn>/tpaccept <text>or <warn>/tpdeny<text>.",
        "tpa.none": "<error>You do not have any pending teleport requests.",
        "tpa.requester-offline": "<error>The requester is no longer online.",
        "tpa.accepted-target": "<success>Teleport request accepted.",
        "tpa.accepted-requester": "<success><warn>%player%<success> accepted your request.",
        "tpa.denied-target": "<success>Teleport request denied.",
        "tpa.denied-requester": "<warn>%player%<error> denied your teleport request.",
        "tpa.cancel-none": "<error>You do not have a pending teleport request to cancel.",
        "tpa.cancelled": "<success>Teleport request cancelled.",
        "rtp.disabled-world": "<error>Random teleport is disabled in this world.",
        "rtp.failed": "<error>Random teleport could not find a safe destination.",
        "rtp.teleported": "<success>Randomly teleported.",
        "teleport.cancelled": "<error>Your teleport was cancelled.",
    },
    "social.yml": {
        "msg.usage": "<error>Usage: <warn>/msg <player> <message>",
        "msg.self": "<error>Sending yourself a DM is not especially productive.",
        "reply.usage": "<error>Usage: <warn>/reply <message>",
        "reply.none": "<error>Nobody has messaged you recently.",
        "ignore.usage": "<error>Usage: <warn>/ignore <player>",
        "ignore.self": "<error>Ignoring yourself is not supported.",
        "ignore.enabled": "<success>You are now ignoring <warn>%player%<success>.",
        "ignore.disabled": "<warn>You are no longer ignoring <text>%player%<warn>.",
        "mail.empty": "<subtle>Your mailbox is empty.",
        "mail.header": "<warn>Your Mail",
        "mail.line": "%marker%#%id% <text>%sender%<subtle>: %body%",
        "mail.send-usage": "<error>Usage: <warn>/mail send <player> <message>",
        "mail.self": "<error>You cannot mail yourself.",
        "mail.received": "<info>You received new mail from <warn>%player%<info>.",
        "mail.sent": "<success>Mail sent to <warn>%player%<success>.",
        "mail.read-usage": "<error>Usage: <warn>/mail read <id>",
        "mail.missing": "<error>No mail entry exists with that id.",
        "mail.from": "<warn>Mail from <text>%sender%",
        "mail.body": "<subtle>%body%",
        "mail.clear-usage": "<error>Usage: <warn>/mail clear <id|all>",
        "mail.cleared": "<success>Your mailbox has been cleared.",
        "mail.removed": "<success>Removed mail from <warn>%sender%<success>.",
        "mail.usage": "<error>Usage: <warn>/mail <send|read|clear|inbox>",
        "mail.unread": "<info>You have <warn>%count%<info> unread mail messages.",
        "nick.usage": "<error>Usage: <warn>/nick <name|off>",
        "nick.cleared": "<success>Your nickname has been cleared.",
        "nick.set": "<success>Nickname set to <warn>%nick%<success>.",
    },
    "kits.yml": {
        "usage": "<error>Usage: <warn>/kit [name]",
        "list-header": "<warn>Available kits<subtle>: <text>%kits%",
        "unknown": "<error>Unknown kit <warn>%kit%<error>.",
        "no-permission": "<error>You do not have permission for kit <warn>%kit%<error>.",
        "cooldown": "<error>Kit <warn>%kit%<error> is on cooldown for <warn>%duration%<error>.",
        "claimed": "<success>Claimed kit <warn>%kit%<success>.",
        "unavailable-profile": "<error>That kit is not available in this world profile.",
        "cannot-afford": "<error>%reason%",
    },
    "staff.yml": {
        "fly.enabled": "<success>Flight enabled.",
        "fly.disabled": "<warn>Flight disabled.",
        "vanish.enabled": "<success>You vanished from regular players.",
        "vanish.disabled": "<warn>You are visible again.",
        "staffmode.enabled": "<success>Staff mode enabled.",
        "staffmode.disabled": "<warn>Staff mode disabled.",
        "socialspy.enabled": "<success>SocialSpy enabled.",
        "socialspy.disabled": "<warn>SocialSpy disabled.",
        "invsee.usage": "<error>Usage: <warn>/invsee <player>",
        "invsee.inspecting": "<success>Inspecting <warn>%player%<success>'s inventory.",
        "endersee.usage": "<error>Usage: <warn>/endersee <player>",
        "endersee.inspecting": "<success>Inspecting <warn>%player%<success>'s ender chest.",
        "seen.usage": "<error>Usage: <warn>/seen <player>",
        "seen.online": "<info><warn>%player% <info>is online now.",
        "seen.offline": "<info><warn>%player% <info>was last seen <warn>%time%<info>.",
        "seen.never": "<error>No join history is available for <warn>%player%<error>.",
    },
    "moderation.yml": {
        "freeze.usage": "<error>Usage: <warn>/freeze <player> [reason]",
        "freeze.done": "<success>Froze <warn>%player%<success>.",
        "freeze.notify": "<error>You have been frozen. Reason: <text>%reason%",
        "unfreeze.usage": "<error>Usage: <warn>/unfreeze <player>",
        "unfreeze.done": "<success>Unfroze <warn>%player%<success>.",
        "unfreeze.notify": "<success>You have been unfrozen.",
        "mute.usage": "<error>Usage: <warn>/mute <player> <duration> [reason]",
        "mute.done": "<success>Muted <warn>%player%<success> for <warn>%duration%<success>.",
        "mute.notify": "<error>You are muted for <warn>%duration%<error>. Reason: <text>%reason%",
        "unmute.usage": "<error>Usage: <warn>/unmute <player>",
        "unmute.done": "<success>Unmuted <warn>%player%<success>.",
        "unmute.notify": "<success>You have been unmuted.",
        "warn.usage": "<error>Usage: <warn>/warn <player> [category] <reason>",
        "warn.done": "<success>Warned <warn>%player%<success>.",
        "warn.notify": "<error>You received a warning: <text>%reason%",
        "kick.usage": "<error>Usage: <warn>/kick <player> [reason]",
        "kick.done": "<success>Kicked <warn>%player%<success>.",
        "kick.message": "<error>You were kicked. Reason: <text>%reason%",
        "tempban.usage": "<error>Usage: <warn>/tempban <player> <duration> [reason]",
        "tempban.done": "<success>Banned <warn>%player%<success> for <warn>%duration%<success>.",
        "tempban.message": "<error>You are banned <warn>%duration%<error>. Reason: <text>%reason%",
        "unban.usage": "<error>Usage: <warn>/unban <player>",
        "unban.done": "<success>Unbanned <warn>%player%<success>.",
        "jail.usage": "<error>Usage: <warn>/jail <player> <jail> [duration] [reason]",
        "jail.done": "<success>Jailed <warn>%player%<success> in <warn>%jail%<success>.",
        "jail.notify": "<error>You have been jailed. Reason: <text>%reason%",
        "jail.active": "<error>You are currently jailed.",
        "unjail.usage": "<error>Usage: <warn>/unjail <player>",
        "unjail.done": "<success>Released <warn>%player%<success> from jail.",
        "unjail.notify": "<success>You have been released from jail.",
        "setjail.usage": "<error>Usage: <warn>/setjail <name>",
        "setjail.done": "<success>Jail <warn>%jail%<success> set at <text>%location%",
        "shadowmute.usage": "<error>Usage: <warn>/shadowmute <player>",
        "shadowmute.enabled": "<success>Shadow mute enabled for <warn>%player%<success>.",
        "shadowmute.disabled": "<warn>Shadow mute disabled for <text>%player%<warn>.",
        "staffnote.usage": "<error>Usage: <warn>/staffnote <player> <note>",
        "staffnote.done": "<success>Added staff note for <warn>%player%<success>.",
        "stafflog.usage": "<error>Usage: <warn>/stafflog <player> [limit]",
        "stafflog.empty": "<subtle>No moderation history found for <text>%player%<subtle>.",
        "stafflog.header": "<warn>Moderation history for <text>%player%",
        "stafflog.line": "<subtle>%time% <info>%action% <subtle>by <text>%actor%<subtle>: %details%",
        "chat.muted": "<error>You are muted for another <warn>%duration%<error>.",
        "chat.frozen": "<error>You cannot chat while frozen.",
        "move.frozen": "<error>You cannot move while frozen.",
        "interact.frozen": "<error>You cannot do that while frozen.",
        "interact.jailed": "<error>You cannot do that while jailed.",
    },
    "admin.yml": {
        "reloaded": "<success>Crossroads has been reloaded.",
        "about": "<accent>Crossroads <text>v%version% <subtle>| storage <text>%storage% <subtle>| economy <text>%economy% <subtle>| language <text>%language%",
        "modules.none": "<subtle>No external modules are loaded.",
        "modules.header": "<warn>Loaded modules",
        "modules.line": "<text>- %name% <subtle>v%version%",
        "backup.usage": "<error>Usage: <warn>/crossroads backup create",
        "backup.created": "<success>Backup created: <warn>%file%",
        "backup.failed": "<error>Backup failed: <text>%reason%",
        "import.usage": "<error>Usage: <warn>/crossroads import essentials",
        "import.done": "<success>Imported Essentials data: <text>%summary%",
        "import.failed": "<error>Import failed: <text>%reason%",
        "language.usage": "<error>Usage: <warn>/language [style|list|sync]",
        "language.list-header": "<warn>Available languages<subtle>: <text>%languages%",
        "language.current": "<info>Your language is <warn>%language%<info>.",
        "language.set": "<success>Language set to <warn>%language%<success>.",
        "language.synced": "<success>Cleared your language override. AegisGuard sync / server default will be used.",
        "language.unknown": "<error>Unknown language <warn>%language%<error>.",
        "language.disabled": "<error>Per-player languages are disabled.",
        "usage": "<error>Usage: <warn>/crossroads <reload|about|modules|backup|import|language|perms>",
    },
    "menus.yml": {
        "warps.title": "Crossroads Warps",
        "warps.lore": "Click to teleport",
        "kits.title": "Crossroads Kits",
        "kits.lore": "Click to claim",
    },
    "economy.yml": {
        "unavailable": "<error>No compatible economy provider is active.",
        "insufficient-funds": "<error>Insufficient funds.",
        "insufficient-claimblocks": "<error>Insufficient AegisGuard ClaimBlocks.",
        "claimblocks-rejected": "<error>AegisGuard rejected the ClaimBlocks transaction.",
        "claimblocks-deposit-unsupported": "<error>ClaimBlocks deposits are not supported here.",
        "claimblocks-set-unsupported": "<error>ClaimBlocks balances cannot be set directly.",
        "transaction-rejected": "<error>The economy provider rejected the transaction.",
        "coffers-failed": "<error>The Coffers transaction failed.",
        "coffers-deposit-unsupported": "<error>Coffers deposits are unavailable.",
        "invalid-amount": "<error>Enter a valid amount greater than zero.",
        "balance.self": "<info>Balance: <warn>%balance%",
        "balance.other": "<info>%player%<subtle>'s balance: <warn>%balance%",
        "balance.usage": "<error>Usage: <warn>/balance [player]",
        "pay.usage": "<error>Usage: <warn>/pay <player> <amount>",
        "pay.self": "<error>You cannot pay yourself.",
        "pay.sent": "<success>Paid <warn>%balance% <success>to <warn>%player%<success>.",
        "pay.received": "<success>You received <warn>%balance% <success>from <warn>%player%<success>.",
        "baltop.header": "<warn>Top balances",
        "baltop.line": "<subtle>#%rank% <text>%player% <subtle>- <warn>%balance%",
        "baltop.empty": "<subtle>No balances to display yet.",
        "eco.usage": "<error>Usage: <warn>/eco <give|take|set> <player> <amount>",
        "eco.give": "<success>Gave <warn>%balance% <success>to <warn>%player%<success>.",
        "eco.take": "<success>Took <warn>%balance% <success>from <warn>%player%<success>.",
        "eco.set": "<success>Set <warn>%player%<success>'s balance to <warn>%balance%<success>.",
        "provider": "<subtle>Economy provider: <text>%provider%",
    },
    "protection.yml": {
        "blocked": "<error>%provider% blocked that teleport. Area: <warn>%area% <error>| Owner: <warn>%owner%",
        "aegisguard-blocked": "<error>AegisGuard blocked that teleport. Plot: <warn>%plot% <error>| Owner: <warn>%owner%",
    },
    "permissions.yml": {
        "disabled": "<error>Crossroads permissions are disabled.",
        "usage": "<error>Usage: <warn>/crperms <user|group|list|check|import>",
        "no-permission": "<error>You do not have permission to manage Crossroads permissions.",
        "user.usage": "<error>Usage: <warn>/crperms user <player> <info|permission|parent|group>",
        "user.info": "<warn>%player% <subtle>| primary <text>%primary% <subtle>| groups <text>%groups%",
        "user.permission-set": "<success>Set <warn>%permission%<success> for <warn>%player%<success> to <text>%value%<success>.",
        "user.permission-unset": "<success>Removed <warn>%permission%<success> from <warn>%player%<success>.",
        "user.parent-add": "<success>Added group <warn>%group%<success> to <warn>%player%<success>.",
        "user.parent-remove": "<success>Removed group <warn>%group%<success> from <warn>%player%<success>.",
        "user.group-set": "<success>Primary group for <warn>%player%<success> set to <warn>%group%<success>.",
        "group.usage": "<error>Usage: <warn>/crperms group <name> <create|delete|info|permission|parent|meta>",
        "group.created": "<success>Created group <warn>%group%<success>.",
        "group.deleted": "<success>Deleted group <warn>%group%<success>.",
        "group.exists": "<error>Group <warn>%group%<error> already exists.",
        "group.missing": "<error>Unknown group <warn>%group%<error>.",
        "group.info": "<warn>%group% <subtle>| weight <text>%weight% <subtle>| parents <text>%parents%",
        "group.permission-set": "<success>Set <warn>%permission%<success> on group <warn>%group%<success> to <text>%value%<success>.",
        "group.permission-unset": "<success>Removed <warn>%permission%<success> from group <warn>%group%<success>.",
        "group.parent-add": "<success>Added parent <warn>%parent%<success> to <warn>%group%<success>.",
        "group.parent-remove": "<success>Removed parent <warn>%parent%<success> from <warn>%group%<success>.",
        "group.meta": "<success>Updated <warn>%group%<success> %field% to <text>%value%<success>.",
        "list.header": "<warn>Groups<subtle>: <text>%groups%",
        "check.result": "<info>%player% <subtle>has <warn>%permission%<subtle>: <text>%value%",
        "import.done": "<success>Imported <warn>%count%<success> LuckPerms groups.",
        "import.none": "<error>No LuckPerms group data was found to import.",
    },
    "welcome.yml": {
        "jailed": "<error>You are currently jailed.",
    },
}

# Lightweight translations: map a few high-traffic phrases; remaining keys keep English structure with translated common words via whole-string maps per language.
TRANSLATIONS: dict[str, dict[str, str]] = {
    "french_fr": {
        "common.no-permission": "<error>Vous n'avez pas la permission.",
        "common.players-only": "<error>Cette commande est réservée aux joueurs.",
        "common.feature-disabled": "<error>Cette fonctionnalité est désactivée dans Crossroads.",
        "common.cooldown": "<error>Commande en cooldown encore <warn>%duration%<error>.",
        "common.player-not-online": "<error>Ce joueur n'est pas en ligne.",
        "common.player-not-found": "<error>Aucun joueur nommé <warn>%player%<error> n'a été trouvé.",
        "travel.home.teleported": "<success>Bienvenue à la maison <warn>%home%<success>.",
        "travel.home.saved": "<success>Maison <warn>%home%<success> enregistrée à <text>%location%",
        "travel.home.none": "<subtle>Vous n'avez encore aucune maison.",
        "travel.warp.teleported": "<success>Téléporté vers <warn>%warp%<success>.",
        "travel.spawn.teleported": "<success>Téléporté au spawn.",
        "travel.back.teleported": "<success>Retour à votre position précédente.",
        "admin.reloaded": "<success>Crossroads a été rechargé.",
        "admin.language.set": "<success>Langue définie sur <warn>%language%<success>.",
        "admin.language.synced": "<success>Préférence de langue effacée. Synchronisation AegisGuard / langue du serveur utilisée.",
        "admin.language.list-header": "<warn>Langues disponibles<subtle>: <text>%languages%",
        "economy.balance.self": "<info>Solde: <warn>%balance%",
        "economy.pay.sent": "<success>Payé <warn>%balance% <success>à <warn>%player%<success>.",
        "economy.insufficient-funds": "<error>Fonds insuffisants.",
        "moderation.kick.message": "<error>Vous avez été expulsé. Raison: <text>%reason%",
        "moderation.tempban.message": "<error>Vous êtes banni <warn>%duration%<error>. Raison: <text>%reason%",
        "menus.warps.title": "Warps Crossroads",
        "menus.kits.title": "Kits Crossroads",
    },
    "spanish_mx": {
        "common.no-permission": "<error>No tienes permiso para eso.",
        "common.players-only": "<error>Este comando solo se puede usar en el juego.",
        "common.feature-disabled": "<error>Esa función está desactivada en Crossroads.",
        "common.cooldown": "<error>Ese comando tiene enfriamiento por <warn>%duration%<error>.",
        "common.player-not-online": "<error>Ese jugador no está en línea.",
        "common.player-not-found": "<error>No se encontró al jugador <warn>%player%<error>.",
        "travel.home.teleported": "<success>Bienvenido a casa <warn>%home%<success>.",
        "travel.home.saved": "<success>Casa <warn>%home%<success> guardada en <text>%location%",
        "travel.home.none": "<subtle>Aún no has establecido casas.",
        "travel.warp.teleported": "<success>Teletransportado a <warn>%warp%<success>.",
        "travel.spawn.teleported": "<success>Teletransportado al spawn.",
        "travel.back.teleported": "<success>Regresaste a tu ubicación anterior.",
        "admin.reloaded": "<success>Crossroads se ha recargado.",
        "admin.language.set": "<success>Idioma establecido a <warn>%language%<success>.",
        "admin.language.synced": "<success>Se borró tu idioma. Se usará sincronización AegisGuard / idioma del servidor.",
        "admin.language.list-header": "<warn>Idiomas disponibles<subtle>: <text>%languages%",
        "economy.balance.self": "<info>Saldo: <warn>%balance%",
        "economy.pay.sent": "<success>Pagaste <warn>%balance% <success>a <warn>%player%<success>.",
        "economy.insufficient-funds": "<error>Fondos insuficientes.",
        "moderation.kick.message": "<error>Fuiste expulsado. Razón: <text>%reason%",
        "moderation.tempban.message": "<error>Estás baneado <warn>%duration%<error>. Razón: <text>%reason%",
        "menus.warps.title": "Warps de Crossroads",
        "menus.kits.title": "Kits de Crossroads",
    },
    "spanish_ar": {},  # filled from spanish_mx below
    "portuguese_br": {
        "common.no-permission": "<error>Você não tem permissão para isso.",
        "common.players-only": "<error>Este comando só pode ser usado no jogo.",
        "common.feature-disabled": "<error>Esse recurso está desativado no Crossroads.",
        "common.cooldown": "<error>Esse comando está em cooldown por mais <warn>%duration%<error>.",
        "common.player-not-online": "<error>Esse jogador não está online.",
        "common.player-not-found": "<error>Nenhum jogador chamado <warn>%player%<error> foi encontrado.",
        "travel.home.teleported": "<success>Bem-vindo de volta à casa <warn>%home%<success>.",
        "travel.home.saved": "<success>Casa <warn>%home%<success> salva em <text>%location%",
        "travel.home.none": "<subtle>Você ainda não definiu casas.",
        "travel.warp.teleported": "<success>Teleportado para <warn>%warp%<success>.",
        "travel.spawn.teleported": "<success>Teleportado para o spawn.",
        "travel.back.teleported": "<success>Voltou para sua localização anterior.",
        "admin.reloaded": "<success>O Crossroads foi recarregado.",
        "admin.language.set": "<success>Idioma definido para <warn>%language%<success>.",
        "admin.language.synced": "<success>Preferência de idioma limpa. Sincronização AegisGuard / padrão do servidor será usada.",
        "admin.language.list-header": "<warn>Idiomas disponíveis<subtle>: <text>%languages%",
        "economy.balance.self": "<info>Saldo: <warn>%balance%",
        "economy.pay.sent": "<success>Pagou <warn>%balance% <success>para <warn>%player%<success>.",
        "economy.insufficient-funds": "<error>Fundos insuficientes.",
        "moderation.kick.message": "<error>Você foi expulso. Motivo: <text>%reason%",
        "moderation.tempban.message": "<error>Você está banido <warn>%duration%<error>. Motivo: <text>%reason%",
        "menus.warps.title": "Warps do Crossroads",
        "menus.kits.title": "Kits do Crossroads",
    },
    "italian_it": {
        "common.no-permission": "<error>Non hai il permesso per farlo.",
        "common.players-only": "<error>Questo comando può essere usato solo in gioco.",
        "common.feature-disabled": "<error>Questa funzione è disabilitata in Crossroads.",
        "common.cooldown": "<error>Comando in cooldown per altri <warn>%duration%<error>.",
        "common.player-not-online": "<error>Quel giocatore non è online.",
        "common.player-not-found": "<error>Nessun giocatore chiamato <warn>%player%<error> trovato.",
        "travel.home.teleported": "<success>Bentornato a casa <warn>%home%<success>.",
        "travel.home.saved": "<success>Casa <warn>%home%<success> salvata a <text>%location%",
        "travel.home.none": "<subtle>Non hai ancora impostato case.",
        "travel.warp.teleported": "<success>Teletrasportato a <warn>%warp%<success>.",
        "travel.spawn.teleported": "<success>Teletrasportato allo spawn.",
        "travel.back.teleported": "<success>Tornato alla posizione precedente.",
        "admin.reloaded": "<success>Crossroads è stato ricaricato.",
        "admin.language.set": "<success>Lingua impostata su <warn>%language%<success>.",
        "admin.language.synced": "<success>Override lingua rimosso. Verrà usata la sync AegisGuard / lingua del server.",
        "admin.language.list-header": "<warn>Lingue disponibili<subtle>: <text>%languages%",
        "economy.balance.self": "<info>Saldo: <warn>%balance%",
        "economy.pay.sent": "<success>Pagato <warn>%balance% <success>a <warn>%player%<success>.",
        "economy.insufficient-funds": "<error>Fondi insufficienti.",
        "moderation.kick.message": "<error>Sei stato espulso. Motivo: <text>%reason%",
        "moderation.tempban.message": "<error>Sei bannato <warn>%duration%<error>. Motivo: <text>%reason%",
        "menus.warps.title": "Warp di Crossroads",
        "menus.kits.title": "Kit di Crossroads",
    },
    "german_de": {
        "common.no-permission": "<error>Dazu hast du keine Berechtigung.",
        "common.players-only": "<error>Dieser Befehl kann nur im Spiel verwendet werden.",
        "common.feature-disabled": "<error>Diese Funktion ist in Crossroads deaktiviert.",
        "common.cooldown": "<error>Dieser Befehl ist noch <warn>%duration%<error> im Cooldown.",
        "common.player-not-online": "<error>Dieser Spieler ist nicht online.",
        "common.player-not-found": "<error>Kein bekannter Spieler namens <warn>%player%<error> gefunden.",
        "travel.home.teleported": "<success>Willkommen zurück bei Zuhause <warn>%home%<success>.",
        "travel.home.saved": "<success>Zuhause <warn>%home%<success> gespeichert bei <text>%location%",
        "travel.home.none": "<subtle>Du hast noch keine Homes gesetzt.",
        "travel.warp.teleported": "<success>Zu <warn>%warp%<success> teleportiert.",
        "travel.spawn.teleported": "<success>Zum Spawn teleportiert.",
        "travel.back.teleported": "<success>Zur vorherigen Position zurückgekehrt.",
        "admin.reloaded": "<success>Crossroads wurde neu geladen.",
        "admin.language.set": "<success>Sprache auf <warn>%language%<success> gesetzt.",
        "admin.language.synced": "<success>Sprach-Override gelöscht. AegisGuard-Sync / Serverstandard wird verwendet.",
        "admin.language.list-header": "<warn>Verfügbare Sprachen<subtle>: <text>%languages%",
        "economy.balance.self": "<info>Guthaben: <warn>%balance%",
        "economy.pay.sent": "<success><warn>%balance% <success>an <warn>%player%<success> gezahlt.",
        "economy.insufficient-funds": "<error>Nicht genug Guthaben.",
        "moderation.kick.message": "<error>Du wurdest gekickt. Grund: <text>%reason%",
        "moderation.tempban.message": "<error>Du bist gebannt <warn>%duration%<error>. Grund: <text>%reason%",
        "menus.warps.title": "Crossroads Warps",
        "menus.kits.title": "Crossroads Kits",
    },
    "polish_pl": {
        "common.no-permission": "<error>Nie masz do tego uprawnień.",
        "common.players-only": "<error>Tej komendy można używać tylko w grze.",
        "common.feature-disabled": "<error>Ta funkcja jest wyłączona w Crossroads.",
        "common.cooldown": "<error>Ta komenda ma cooldown jeszcze przez <warn>%duration%<error>.",
        "common.player-not-online": "<error>Ten gracz nie jest online.",
        "common.player-not-found": "<error>Nie znaleziono gracza o nazwie <warn>%player%<error>.",
        "travel.home.teleported": "<success>Witaj z powrotem w domu <warn>%home%<success>.",
        "travel.home.saved": "<success>Zapisano dom <warn>%home%<success> w <text>%location%",
        "travel.home.none": "<subtle>Nie ustawiłeś jeszcze żadnych domów.",
        "travel.warp.teleported": "<success>Przeteleportowano do <warn>%warp%<success>.",
        "travel.spawn.teleported": "<success>Przeteleportowano na spawn.",
        "travel.back.teleported": "<success>Wrócono do poprzedniej lokalizacji.",
        "admin.reloaded": "<success>Crossroads został przeładowany.",
        "admin.language.set": "<success>Język ustawiony na <warn>%language%<success>.",
        "admin.language.synced": "<success>Wyczyszczono nadpisanie języka. Użyte zostanie sync AegisGuard / domyślny język serwera.",
        "admin.language.list-header": "<warn>Dostępne języki<subtle>: <text>%languages%",
        "economy.balance.self": "<info>Saldo: <warn>%balance%",
        "economy.pay.sent": "<success>Zapłacono <warn>%balance% <success>dla <warn>%player%<success>.",
        "economy.insufficient-funds": "<error>Niewystarczające środki.",
        "moderation.kick.message": "<error>Zostałeś wyrzucony. Powód: <text>%reason%",
        "moderation.tempban.message": "<error>Jesteś zbanowany <warn>%duration%<error>. Powód: <text>%reason%",
        "menus.warps.title": "Warpy Crossroads",
        "menus.kits.title": "Zestawy Crossroads",
    },
}

TRANSLATIONS["spanish_ar"] = dict(TRANSLATIONS["spanish_mx"])


def nested_set(tree: dict, dotted: str, value: str) -> None:
    parts = dotted.split(".")
    node = tree
    for part in parts[:-1]:
        node = node.setdefault(part, {})
    node[parts[-1]] = value


def dump_yaml(tree: dict, indent: int = 0) -> list[str]:
    lines: list[str] = []
    for key, value in tree.items():
        if isinstance(value, dict):
            lines.append("  " * indent + f"{key}:")
            lines.extend(dump_yaml(value, indent + 1))
        else:
            escaped = str(value).replace("'", "''")
            lines.append("  " * indent + f"{key}: '{escaped}'")
    return lines


def write_language(language: str, overrides: dict[str, str]) -> None:
    # Build flat map from English, apply overrides
    for bundle, entries in EN.items():
        tree: dict = {}
        for key, english in entries.items():
            full = f"{bundle[:-4]}.{key}" if False else key
            # Keys in EN are already relative to bundle conceptually for nested paths
            # Store under nested path from key; prefix with bundle stem only for override lookup
            override_key = f"{Path(bundle).stem}.{key}"
            value = overrides.get(override_key, english)
            nested_set(tree, key, value)
        out_dir = ROOT / language
        out_dir.mkdir(parents=True, exist_ok=True)
        content = "\n".join(dump_yaml(tree)) + "\n"
        (out_dir / bundle).write_text(content, encoding="utf-8")


def main() -> None:
    write_language("modern_english", {})
    for language, overrides in TRANSLATIONS.items():
        # Start from English full pack, overlay translations (fallback to English for untranslated keys)
        write_language(language, overrides)
    print("Generated language packs in", ROOT)


if __name__ == "__main__":
    main()
